name: tensoltest
description: A Flutter application for TensorFlow image recognition.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI関連
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.3.5

  # 機械学習関連
  tflite: ^1.1.2

  # カメラ・メディア関連
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  video_player: ^2.7.2
  
  # ファイル・ストレージ関連
  path_provider: ^2.1.1
  path: ^1.8.3

  # Firebase関連
  firebase_core: ^2.15.1
  google_mobile_ads: ^3.0.0  # firebase_admob の代替として

  # コード品質関連
  pedantic: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
